language: ruby
rvm:
- 2.6.6
install: gem install jekyll
script:
- bundle install
- bundle exec jekyll build
before_install:
addons: ssh_known_hosts:52.74.223.119
after_success:
- git clone https://github.com/gangdong/daviddong.github.io.git
- cd daviddong.github.io && rm -rf * && cp -r ../_site/* .
- git config user.name "gangdong"
- git config user.email "dqdongg@hotmail.com"
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git remote add origin git@github.com:gangdong/daviddong.github.io.git
- git push --force origin master:test_travisci
