language: ruby
rvm:
- 2.6.6
install: gem install jekyll
script:
- bundle install
- bundle exec jekyll build
before_install:
- openssl aes-256-cbc -K $encrypted_534a289dd418_key -iv $encrypted_534a289dd418_iv
  -in id_rsa.enc -out C:\\Users\\david.dong\\githubkey\\.ssh\\id_rsa -d
addons: ssh_known_hosts:52.74.223.119
